WITH application_base AS (
    SELECT * FROM {{ ref('int_application_base') }}
),
bureau_client        AS (SELECT * FROM {{ ref('int_bureau_client_agg') }}),
credit_card_balance  AS (SELECT * FROM {{ ref('int_credit_card_balance_agg') }}),
installment_payment  AS (SELECT * FROM {{ ref('int_installments_payments_agg') }}),
pos_cash_balance     AS (SELECT * FROM {{ ref('int_POS_cash_balance_agg') }}),
previous_application AS (SELECT * FROM {{ ref('int_previous_application_agg') }}),
final AS (
    SELECT
        ap.loan_id,
        ap.target,
        ap.contract_type,
        ap.gender,
        ap.own_car,
        ap.own_realty,
        ap.num_children,
        ap.annual_income,
        ap.total_loan_amount,
        ap.monthly_loan_amount,
        ap.goods_price,
        ap.income_type,
        ap.education_type,
        ap.family_status,
        ap.housing_type,
        ap.days_birth,
        ap.days_employed,
        ap.days_employed_clean,
        ap.days_id_publish,
        ap.extra_sources,
        ap.occupation_type,
        ap.num_family_members,
        ap.region_rating_city,
        ap.organization_type,
        ap.days_last_phone_change,
        ap.is_employment_anomaly,
        bc.bureau_num_credits,
        bc.num_active_credits,
        bc.num_curr_overdue,
        bc.num_overdue_credits,
        bc.num_prolonged_credits,
        bc.total_debt,
        bc.oldest_credit_days,
        bc.newest_credit_days,
        bc.num_credits_last_year,
        bc.num_long_term,
        bc.num_short_term,
        bc.num_business_credits,
        bc.most_common_status,
        bc.has_high_risk_status,
        pc.total_prev_installments,
        pc.total_future_installments,
        pc.most_contract_type,
        pc.total_dpd_def,
        ip.avg_delay,
        ip.late_count,
        ip.total_paid,
        ip.total_remaining,
        pa.total_previous_applications,
        pa.unique_contract_types,
        pa.num_approved,
        pa.num_refused,
        pa.num_canceled,
        pa.avg_annuity_amount,
        pa.avg_loan_amount,
        pa.avg_down_payment,
        pa.most_contract_type,
        pa.most_yield_group,
        pa.most_client_type,
        pa.total_is_insured,
        cc.months_observed,
        cc.avg_balance,
        cc.max_balance,
        cc.avg_credit_limit,
        cc.max_credit_limit,
        cc.avg_utilization_ratio,
        cc.total_drawings,
        cc.total_payments_made,
        cc.avg_total_receivable,
        cc.max_total_receivable,
        cc.months_with_dpd,
        cc.ever_over_limit_flag
    FROM application_base ap
    LEFT JOIN bureau_client bc          ON ap.loan_id = bc.client_id
    LEFT JOIN pos_cash_balance pc       ON ap.loan_id = pc.client_id
    LEFT JOIN installment_payment ip    ON ap.loan_id = ip.client_id
    LEFT JOIN previous_application pa   ON ap.loan_id = pa.client_id
    LEFT JOIN credit_card_balance cc    ON ap.loan_id = cc.client_id
)
SELECT * FROM final