SELECT
    SK_ID_CURR AS member_id,
    NAME_CONTRACT_TYPE AS contract_type,
    CODE_GENDER AS gender,
    FLAG_OWN_CAR AS own_car,
    FLAG_OWN_REALTY AS own_realty,
    CNT_CHILDREN AS num_children,
    AMT_INCOME_TOTAL AS annual_income,
    AMT_CREDIT AS total_loan_amount,
    AMT_ANNUITY AS monthly_loan_amount,
    AMT_GOODS_PRICE AS goods_price,
    NAME_INCOME_TYPE AS job_type,
    NAME_EDUCATION_TYPE AS education_type,
    NAME_FAMILY_STATUS AS family_status,
    NAME_HOUSING_TYPE AS housing_type,
    DAYS_BIRTH AS age_day_application,
    DAYS_EMPLOYED AS days_employed,
    DAYS_ID_PUBLISH AS days_id_changed,
    OCCUPATION_TYPE AS occupation_type,
    CNT_FAM_MEMBERS AS num_family_members,
    REGION_RATING_CLIENT_W_CITY AS region_rating_city,
    ORGANIZATION_TYPE AS oragnazation_type,
    (EXT_SOURCE_1 + EXT_SOURCE_2 + EXT_SOURCE_3) / 3 AS avg_external_sources,
    OBS_60_CNT_SOCIAL_CIRCLE AS observed_social_circle,
    DEF_60_CNT_SOCIAL_CIRCLE AS default_social_circle,
    DAYS_LAST_PHONE_CHANGE AS days_last_phone_change,
    AMT_REQ_CREDIT_BUREAU_MON AS bureau_credit_request_last_month,
    AMT_REQ_CREDIT_BUREAU_YEAR AS bureau_credit_request_last_year,
    TARGET as target
FROM {{ source('raw', 'application_train') }}